import { useEffect, useRef, useState } from 'react';
import { EXPLAINER_STORYBOARD } from '../media/explainerStoryboard';
import { parallaxMedia } from '../media/parallaxMedia';

const guideMessages: Record<string, string> = {
  INTRO: 'Give me a spatial objective. I’ll determine what needs to change.', OBSERVE: 'I’m mapping the environment and identifying the relevant objects.', REQUEST: 'I found the object. Now I’m requesting only the spatial capability I need.', AUTHORIZE: 'Identity, mandate and policy determine whether this action is allowed.', ACT: 'Authorization passed. I’m applying the bounded change now.', SEE_AGAIN: 'I don’t assume the action succeeded. I’m observing the environment again.', VERIFY: 'I’m comparing the observed result with the original objective.', RECEIPT: 'The result is verified. I’m recording exactly what happened.', DENIAL: 'This action is outside the allowed scope, so PARALLAX blocks it and leaves the world unchanged.', COMPLETE: 'Authorized changes were verified. Unauthorized changes were denied. That’s the PARALLAX loop.',
};

export function ParallaxExplainer({ reducedMotion }: { reducedMotion: boolean }) {
  const storyRef = useRef<HTMLDivElement>(null); const [active, setActive] = useState(0); const [autoTour, setAutoTour] = useState(!reducedMotion); const stage = EXPLAINER_STORYBOARD[active];
  useEffect(() => { if (!autoTour || reducedMotion) return; const timer = window.setTimeout(() => { const next = (active + 1) % EXPLAINER_STORYBOARD.length; storyRef.current?.children[next]?.scrollIntoView({ behavior: 'smooth' }); setActive(next); }, stage.durationMs); return () => window.clearTimeout(timer); }, [active, autoTour, reducedMotion, stage.durationMs]);
  useEffect(() => { const node = storyRef.current; if (!node) return; const onScroll = () => { const index = Math.round(node.scrollTop / node.clientHeight); if (index !== active) { setActive(Math.max(0, Math.min(EXPLAINER_STORYBOARD.length - 1, index))); setAutoTour(false); } }; node.addEventListener('scroll', onScroll, { passive: true }); return () => node.removeEventListener('scroll', onScroll); }, [active]);
  const go = (index: number) => { setActive(index); setAutoTour(false); storyRef.current?.children[index]?.scrollIntoView({ behavior: reducedMotion ? 'auto' : 'smooth' }); };
  return <section className="parallax-loop-story" aria-labelledby="explainer-title"><header className="section-intro parallax-loop-story-header"><p className="section-kicker">THE PARALLAX LOOP</p><h2 id="explainer-title">One governed story, from intent to proof.</h2><span className="parallax-explainer-label">ILLUSTRATED PARALLAX LOOP · GUIDED EXPLAINER</span><div className="story-controls"><button type="button" onClick={() => setAutoTour((value) => !value)}>{autoTour ? 'PAUSE TOUR' : 'AUTO TOUR'}</button><button type="button" onClick={() => go((active + EXPLAINER_STORYBOARD.length - 1) % EXPLAINER_STORYBOARD.length)}>PREVIOUS</button><button type="button" onClick={() => go((active + 1) % EXPLAINER_STORYBOARD.length)}>NEXT</button></div></header><div ref={storyRef} className="parallax-story-feed" onPointerDown={() => setAutoTour(false)}>{EXPLAINER_STORYBOARD.map((item, index) => <article className={`parallax-story-stage ${index === active ? 'is-active' : ''}`} key={item.id}>{item.media && !reducedMotion && index === active ? <video className="parallax-story-media" autoPlay muted playsInline preload="metadata" poster={parallaxMedia.fallbackImage} src={item.media} onEnded={() => go((index + 1) % EXPLAINER_STORYBOARD.length)} /> : <img className="parallax-story-media" src={parallaxMedia.establishingImage} alt="" /> }<div className="parallax-story-veil" /><div className="parallax-story-copy"><span>{String(index + 1).padStart(2, '0')} / {String(EXPLAINER_STORYBOARD.length).padStart(2, '0')}</span><strong>{item.title}</strong><p>{item.copy}</p><small>{item.protocol}</small></div></article>)}</div><aside className="parallax-guide" aria-live="polite"><div className="parallax-guide-avatar">P</div><div><strong>PARALLAX GUIDE</strong><span>Spatial Operator · {stage.title}</span><p>{guideMessages[stage.id]}</p></div></aside><nav className="parallax-story-dots" aria-label="Story stages">{EXPLAINER_STORYBOARD.map((item, index) => <button key={item.id} type="button" aria-label={`Go to ${item.title}`} className={index === active ? 'is-active' : ''} onClick={() => go(index)} />)}</nav><div className="parallax-story-handoff"><strong>LOOP EXPLAINS · LIVE DEMO PROVES</strong><button type="button" onClick={() => document.getElementById('interactive-demo')?.scrollIntoView({ behavior: reducedMotion ? 'auto' : 'smooth' })}>RUN LIVE PARALLAX</button></div></section>;
}

export { ParallaxExplainer as ParallaxLoopStory };
