import type {
  VaultAccessibilityCapability,
  VaultComponentManifest,
  VaultGpuCost,
  VaultInteractionKind,
  VaultSurfaceKind,
} from './types'

const today = '2026-09-01'

function reviewedManifest(manifest: VaultComponentManifest): VaultComponentManifest {
  return manifest
}

function registryMeta(
  surfaces: VaultSurfaceKind[],
  interactions: VaultInteractionKind[],
  gpuCost: VaultGpuCost,
  accessibility: VaultAccessibilityCapability[] = ['reduced-motion'],
) {
  return {
    surfaces,
    interactions,
    gpuCost,
    accessibility,
  }
}

export const initialVaultManifests: VaultComponentManifest[] = [
  reviewedManifest({
    id: 'orbit.integrations',
    name: 'Orbit Integrations',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'navigation', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['all'], reducedMotionFallback: 'Static keyboard-first segmented navigation.' },
    registry: registryMeta(['navigation'], ['navigate', 'inspect'], 'none', ['keyboard', 'focus-visible', 'reduced-motion']),
    localModifications: ['Local API stabilized for AGENTROPOLIS route and district navigation contexts.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'spatial.poem-cube',
    name: 'Spatial Poem Cube',
    version: '0.1.0',
    source: { provider: 'quarantine-mirror', sourceUrl: null, retrievedAt: null, originalAuthor: null, license: null },
    classification: { category: 'spatial', maturity: 'quarantine', clientOnly: true, gpuRequired: true, mobileSafe: true, runtime: 'Three.js' },
    dependencies: ['react', 'three'],
    agentropolis: { systemWide: true, districts: ['hermes-city', 'district-scenes'], applications: ['story surfaces'], reducedMotionFallback: 'Render static face copy with keyboard-advance controls.' },
    registry: registryMeta(['spatial-display'], ['inspect'], 'high', ['keyboard', 'reduced-motion']),
    localModifications: ['Adapter-backed local fallback implementation used until upstream source retrieval is complete.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'motion.perspective-marquee',
    name: 'Perspective Marquee',
    version: '0.1.0',
    source: { provider: 'quarantine-mirror', sourceUrl: null, retrievedAt: null, originalAuthor: null, license: null },
    classification: { category: 'motion', maturity: 'quarantine', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'CSS' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['marketing', 'district labels'], reducedMotionFallback: 'Switch to a non-animated stacked list.' },
    registry: registryMeta(['section-title'], ['static'], 'none', ['reduced-motion']),
    localModifications: ['Uses CSS animation with prefers-reduced-motion fallback and AGENTROPOLIS tokens.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'shader.atc',
    name: 'ATC Shader Panel',
    version: '0.1.0',
    source: { provider: 'quarantine-mirror', sourceUrl: null, retrievedAt: null, originalAuthor: null, license: null },
    classification: { category: 'shaders', maturity: 'quarantine', clientOnly: true, gpuRequired: true, mobileSafe: false, runtime: 'WebGL/WebGL2' },
    dependencies: ['react', 'three'],
    agentropolis: { systemWide: false, districts: ['atc', 'world-scenes'], applications: ['hero surfaces'], reducedMotionFallback: 'Static gradient panel with no render loop.' },
    registry: registryMeta(['shader-panel'], ['inspect'], 'high', ['reduced-motion']),
    localModifications: ['Exposed as an adapter-backed panel, not a mandatory scene runtime.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'action.energy-cta',
    name: 'Energy CTA',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'action', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['webmcp', 'mission-control'], applications: ['all'], reducedMotionFallback: 'No animation required.' },
    registry: registryMeta(['cta'], ['activate'], 'none', ['keyboard', 'focus-visible', 'reduced-motion']),
    localModifications: ['Normalized CTA layout and semantic props for AGENTROPOLIS call-to-action surfaces.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'loader.assembly-cube',
    name: 'Assembly Cube Loader',
    version: '0.1.0',
    source: { provider: 'quarantine-mirror', sourceUrl: null, retrievedAt: null, originalAuthor: null, license: null },
    classification: { category: 'loaders', maturity: 'quarantine', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'CSS' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['all'], reducedMotionFallback: 'Static assembly frame.' },
    registry: registryMeta(['loader'], ['static'], 'low', ['reduced-motion']),
    localModifications: ['Local CSS fallback avoids mandatory WebGL for loading states.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'receipt.tool-calls',
    name: 'Tool Calls Section',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['webmcp', 'mission-control'], applications: ['audit', 'ops'], reducedMotionFallback: 'No motion required.' },
    registry: registryMeta(['receipt'], ['inspect'], 'none', ['keyboard', 'aria-label', 'reduced-motion']),
    localModifications: ['Local schema accepts governed tool lifecycle records and receipt output.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'gallery.stellar',
    name: 'Stellar Gallery',
    version: '0.1.0',
    source: { provider: 'quarantine-mirror', sourceUrl: null, retrievedAt: null, originalAuthor: null, license: null },
    classification: { category: 'galleries', maturity: 'quarantine', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['789-studios', 'webmcp'], applications: ['portfolio', 'showcase'], reducedMotionFallback: 'Static responsive grid.' },
    registry: registryMeta(['gallery'], ['inspect'], 'none', ['alt-text', 'keyboard', 'reduced-motion']),
    localModifications: ['Local theme tokens applied; no remote assets required.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'gallery.folder',
    name: 'Folder Gallery',
    version: '0.1.0',
    source: { provider: 'quarantine-mirror', sourceUrl: null, retrievedAt: null, originalAuthor: null, license: null },
    classification: { category: 'galleries', maturity: 'quarantine', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['webmcp', 'archives'], applications: ['asset browsers'], reducedMotionFallback: 'Static folder list with keyboard navigation.' },
    registry: registryMeta(['gallery'], ['select', 'inspect'], 'none', ['keyboard', 'focus-visible', 'reduced-motion']),
    localModifications: ['Folder state normalized for keyboard and alt text support.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'gallery.sphere',
    name: 'Sphere Image Grid',
    version: '0.1.0',
    source: { provider: 'quarantine-mirror', sourceUrl: null, retrievedAt: null, originalAuthor: null, license: null },
    classification: { category: 'galleries', maturity: 'quarantine', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['789-studios', 'hermes-city'], applications: ['showcases', 'agent profiles'], reducedMotionFallback: 'Static rounded card grid.' },
    registry: registryMeta(['gallery'], ['inspect'], 'none', ['alt-text', 'reduced-motion']),
    localModifications: ['Local DOM fallback retains alt text and avoids parallel GPU loops.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'receipt.execution-receipt',
    name: 'Execution Receipt',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['webmcp', 'mission-control'], applications: ['audit', 'governance'], reducedMotionFallback: 'No motion required.' },
    registry: registryMeta(['receipt'], ['inspect'], 'none', ['keyboard', 'aria-label', 'reduced-motion']),
    localModifications: ['Local governed adapter for AGENTROPOLIS execution receipts.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'agent.credential',
    name: 'Agent Credential',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['hermes-city', 'webmcp'], applications: ['agents', 'district shells'], reducedMotionFallback: 'No motion required.' },
    registry: registryMeta(['credential'], ['inspect'], 'none', ['aria-label', 'reduced-motion']),
    localModifications: ['Local governed adapter for actor credential display and mandate signaling.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'integration.constellation',
    name: 'Integration Constellation',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'navigation', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['webmcp', 'mission-control', 'hermes-city'], applications: ['integrations', 'dashboards'], reducedMotionFallback: 'Static node list with badges.' },
    registry: registryMeta(['navigation'], ['navigate', 'inspect'], 'none', ['keyboard', 'reduced-motion']),
    localModifications: ['Local governed adapter for integration status maps without mandatory WebGL.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.universal-district-shell',
    name: 'Universal District Shell',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'navigation', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['district shells', 'ops'], reducedMotionFallback: 'Static shell with no autonomous motion requirements.' },
    registry: registryMeta(['district-shell'], ['compose', 'navigate'], 'none', ['keyboard', 'focus-visible', 'reduced-motion']),
    localModifications: ['Obsidian Signal shell layer added for district-scale composition without replacing the shared core foundation.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'navigation.system-nav',
    name: 'System Nav',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'navigation', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['district shells', 'ops'], reducedMotionFallback: 'Static segmented navigation with keyboard activation.' },
    registry: registryMeta(['navigation'], ['navigate', 'select'], 'none', ['keyboard', 'focus-visible', 'reduced-motion']),
    localModifications: ['District-aware accent routing inherits Obsidian Signal core tokens rather than replacing them.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.command-header',
    name: 'Command Header',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['district shells', 'ops'], reducedMotionFallback: 'Static heading with no required animation.' },
    registry: registryMeta(['header'], ['inspect'], 'none', ['aria-label', 'reduced-motion']),
    localModifications: ['Institutional header pattern grounded in Obsidian Signal shell language.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.signal-card',
    name: 'Signal Card',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['district shells', 'ops'], reducedMotionFallback: 'Static card with semantic status color only.' },
    registry: registryMeta(['card'], ['inspect'], 'none', ['aria-label', 'reduced-motion']),
    localModifications: ['Core card primitive preserves the shared foundation and uses accent only as a district extension.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.operation-card',
    name: 'Operation Card',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['ops', 'governance'], reducedMotionFallback: 'Static operation summary and metadata chips.' },
    registry: registryMeta(['card'], ['inspect'], 'none', ['aria-label', 'reduced-motion']),
    localModifications: ['Operation framing added for governance and receipt surfaces.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.status-chip',
    name: 'Status Chip',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['all'], reducedMotionFallback: 'Static chip with semantic color only.' },
    registry: registryMeta(['badge'], ['inspect'], 'none', ['aria-label', 'reduced-motion']),
    localModifications: ['Unified status representation across shell, governance, and receipt surfaces.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.district-badge',
    name: 'District Badge',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['district shells', 'ops'], reducedMotionFallback: 'Static district marker using inherited core tokens plus accent extension.' },
    registry: registryMeta(['badge'], ['inspect'], 'none', ['aria-label', 'reduced-motion']),
    localModifications: ['District identity constrained to accent extension only.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.section-title',
    name: 'Section Title',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['district shells', 'ops'], reducedMotionFallback: 'Static title with accent kicker only.' },
    registry: registryMeta(['section-title'], ['inspect'], 'none', ['aria-label', 'reduced-motion']),
    localModifications: ['Section title inherits the shared shell heading language.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.hud-divider',
    name: 'HUD Divider',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'tool-ui', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['district shells', 'ops'], reducedMotionFallback: 'Static divider line with no animation.' },
    registry: registryMeta(['divider'], ['static'], 'none', ['reduced-motion']),
    localModifications: ['Environmental HUD separator for shell subdivisions.'],
    agentropolisVersion: '0.1.0',
  }),
  reviewedManifest({
    id: 'system.system-footer',
    name: 'System Footer',
    version: '0.1.0',
    source: { provider: 'local-adapter', sourceUrl: null, retrievedAt: today, originalAuthor: null, license: 'Apache-2.0' },
    classification: { category: 'navigation', maturity: 'reviewed', clientOnly: false, gpuRequired: false, mobileSafe: true, runtime: 'DOM' },
    dependencies: ['react'],
    agentropolis: { systemWide: true, districts: ['all'], applications: ['district shells', 'ops'], reducedMotionFallback: 'Static footer metadata cluster.' },
    registry: registryMeta(['footer'], ['inspect'], 'none', ['aria-label', 'reduced-motion']),
    localModifications: ['Footer pattern aligned to shell and receipt boundaries.'],
    agentropolisVersion: '0.1.0',
  }),
]
